sonar.projectKey=devsecblueprint_devsecblueprint_4b382cb2-090e-4a59-821f-d7cd711d1705
sonar.sources=backend,frontend,terraform,tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=frontend/lib/curriculum-data.ts,**/node_modules/**,**/.terraform/**,**/*.tfstate,**/*.tfstate.*,**/dist/**,**/build/**,**/__pycache__/**,**/*.pyc
sonar.python.version=3.12
