sonar.projectKey=devsecblueprint_devsecblueprint
sonar.projectName=devsecblueprint/devsecblueprint
sonar.organization=devsecblueprint
sonar.sources=backend,frontend,terraform,tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=frontend/lib/curriculum-data.ts,**/node_modules/**,**/.terraform/**,**/*.tfstate,**/*.tfstate.*,**/dist/**,**/build/**,**/__pycache__/**,**/*.pyc
sonar.python.version=3.12
