#!/usr/bin/env tsx
/**
 * Generate walkthroughs-data.ts from actual content
 * 
 * This script reads all walkthrough metadata.json files and generates
 * the WALKTHROUGHS_DATA constant for client-side use.
 */

import * as fs from 'fs';
import * as path from 'path';

interface WalkthroughMetadata {
  id: string;
  title: string;
  description: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  topics: string[];
  estimatedTime: number;
  prerequisites: string[];
  repository: string;
  repositoryUrl?: string;
  authors?: Array<{ name: string; url?: string }>;
}

const WALKTHROUGHS_DIR = path.join(process.cwd(), 'content', 'walkthroughs');
const OUTPUT_FILE = path.join(process.cwd(), 'lib', 'walkthroughs-data.ts');

function loadWalkthroughMetadata(folderPath: string): WalkthroughMetadata | null {
  const metadataPath = path.join(folderPath, 'metadata.json');
  
  if (!fs.existsSync(metadataPath)) {
    return null;
  }
  
  try {
    const content = fs.readFileSync(metadataPath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.error(`Failed to parse metadata from ${metadataPath}:`, error);
    return null;
  }
}

function generateWalkthroughsData(): void {
  const walkthroughs: WalkthroughMetadata[] = [];
  
  // Read all walkthrough folders
  const folders = fs.readdirSync(WALKTHROUGHS_DIR, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);
  
  console.log(`Found ${folders.length} walkthrough folders`);
  
  // Load metadata from each folder
  for (const folder of folders) {
    const folderPath = path.join(WALKTHROUGHS_DIR, folder);
    const metadata = loadWalkthroughMetadata(folderPath);
    
    if (metadata) {
      walkthroughs.push(metadata);
      console.log(`✓ Loaded: ${metadata.id} - ${metadata.title}`);
    } else {
      console.warn(`✗ Skipped: ${folder} (no valid metadata.json)`);
    }
  }
  
  // Sort by difficulty (Beginner -> Intermediate -> Advanced)
  const difficultyOrder = { 'Beginner': 1, 'Intermediate': 2, 'Advanced': 3 };
  walkthroughs.sort((a, b) => {
    const diffA = difficultyOrder[a.difficulty] || 999;
    const diffB = difficultyOrder[b.difficulty] || 999;
    return diffA - diffB;
  });
  
  // Generate TypeScript file
  const fileContent = `/**
 * Pre-loaded walkthrough data for client-side use
 * This file is generated at build time and contains all walkthrough metadata
 * 
 * Generated by: scripts/generate-walkthroughs-data.ts
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 */

import type { Walkthrough } from '@/lib/types';

// This data is embedded at build time
export const WALKTHROUGHS_DATA: Walkthrough[] = ${JSON.stringify(walkthroughs, null, 2)};
`;
  
  // Write to output file
  fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf-8');
  
  console.log(`\n✓ Generated ${OUTPUT_FILE} with ${walkthroughs.length} walkthroughs`);
}

// Run the generator
generateWalkthroughsData();
