/**
 * Pre-loaded walkthrough data for client-side use
 * This file is generated at build time and contains all walkthrough metadata
 * 
 * Generated by: scripts/generate-walkthroughs-data.ts
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 */

import type { Walkthrough } from '@/lib/types';

// This data is embedded at build time
export const WALKTHROUGHS_DATA: Walkthrough[] = [
  {
    "id": "aws-detective-control",
    "title": "Event-Driven S3 Public Access Detective Control",
    "description": "Implement an automated security control to catch S3 bucket misconfigurations as they happen. This project leverages CloudTrail and EventBridge to trigger a Python-based Lambda function that evaluates live bucket settings and sends actionable alerts via SNS.",
    "difficulty": "Beginner",
    "topics": [
      "AWS",
      "Cloud Security",
      "Detection Engineering",
      "Lambda",
      "Event-Driven Architecture",
      "Terraform"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "AWS Account",
      "Terraform CLI",
      "Basic Python Proficiency",
      "Knowledge of IAM Policies"
    ],
    "repository": "walkthroughs/aws-detective-control",
    "repositoryUrl": "https://github.com/devsecblueprint/aws-event-driven-s3-public-detective-control",
    "authors": [
      {
        "name": "Kosisochukwu Akaeze",
        "url": "https://www.linkedin.com/in/kosisochukwu-akaeze-a4853a1a7"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "azure-policy-fundamentals",
    "title": "Azure Policy Fundamentals",
    "description": "Build a complete mental model of Azure Policy before writing any JSON or Terraform. Covers evaluation triggers, policy effects, the definition JSON schema, mode selection, parameters, policy rules, and how initiatives, assignments, and exemptions work together to govern an Azure environment.",
    "difficulty": "Beginner",
    "topics": [
      "Azure",
      "Cloud Security",
      "Governance",
      "Azure Policy",
      "Policy as Code",
      "Compliance"
    ],
    "estimatedTime": 240,
    "prerequisites": [
      "Azure Account",
      "Basic familiarity with Azure (resource groups, subscriptions, management groups)",
      "Basic familiarity with JSON syntax"
    ],
    "repository": "walkthroughs/azure-policy-fundamentals",
    "repositoryUrl": "https://github.com/devsecblueprint/azure-policy-as-code",
    "authors": [
      {
        "name": "Timothy Hogue",
        "url": "https://www.linkedin.com/in/timothy-hogue"
      }
    ]
  },
  {
    "id": "azure-storage-public-exposure-detection",
    "title": "Azure Storage Public Exposure Detective Control",
    "description": "Build a Python-based detective control that scans Azure Storage accounts for risky public exposure configurations, generates structured JSON findings, and sends actionable email alerts via Azure Communication Services.",
    "difficulty": "Beginner",
    "topics": [
      "Azure",
      "Cloud Security",
      "Detection Engineering",
      "Python",
      "Azure Communication Services",
      "Azure Resource Graph"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "Azure Account",
      "Python 3.11+",
      "Azure CLI",
      "Basic Python Proficiency",
      "Knowledge of Azure RBAC"
    ],
    "repository": "walkthroughs/azure-storage-public-exposure-detection",
    "repositoryUrl": "https://github.com/devsecblueprint/azure-storage-public-exposure-detective-control",
    "authors": [
      {
        "name": "Timothy Hogue",
        "url": "https://www.linkedin.com/in/timothy-hogue"
      }
    ]
  },
  {
    "id": "devsecops-pipeline-gha",
    "title": "GitHub Actions DevSecOps Pipeline",
    "description": "Build a fully automated DevSecOps pipeline using GitHub Actions. This lab integrates SAST with SonarCloud, DAST with ZAP, and container scanning with Trivy to secure a Python FastAPI application and publish it to the GitHub Container Registry (GHCR).",
    "difficulty": "Beginner",
    "topics": [
      "GitHub Actions",
      "SAST/DAST",
      "Trivy",
      "SonarCloud",
      "GHCR",
      "FastAPI"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "GitHub Account",
      "Basic knowledge of Docker",
      "Understanding of YAML for Workflows",
      "Python 3.12+"
    ],
    "repository": "walkthroughs/devsecops-pipeline-gha",
    "repositoryUrl": "https://github.com/devsecblueprint/python-fastapi",
    "authors": [
      {
        "name": "Timothy Hogue",
        "url": "https://www.linkedin.com/in/timothy-hogue/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "install-helm-ubuntu",
    "title": "Installing Helm and Deploying an Application on Ubuntu Desktop in VirtualBox",
    "description": "Install Helm with apt inside an Ubuntu Desktop VirtualBox VM, create a Helm chart, and deploy Chainguard NGINX into the default namespace. Configure NodePort access, validate connectivity, and learn how to inspect, upgrade, roll back, package, and remove Helm releases.",
    "difficulty": "Beginner",
    "topics": [
      "Helm",
      "Kubernetes",
      "NGINX",
      "Chainguard",
      "Helm Charts",
      "NodePort",
      "Ubuntu",
      "VirtualBox"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "Ubuntu Desktop VM running in VirtualBox",
      "Ubuntu user account with sudo access",
      "Working Kubernetes cluster with a node ready to schedule workloads",
      "kubectl and a configured kubeconfig",
      "Permission to manage application resources and Helm release Secrets in the default namespace",
      "Internet access to package repositories and cgr.dev",
      "Basic Linux command-line and YAML familiarity"
    ],
    "repository": "walkthroughs/install-helm-ubuntu",
    "authors": [
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "single-node-k8s-cluster",
    "title": "Single-Node Kubernetes Cluster with kubeadm",
    "description": "Build a single-node Kubernetes cluster in an Ubuntu VirtualBox virtual machine using kubeadm, containerd, and Calico. This walkthrough covers host preparation, control-plane initialization, Pod networking, workload deployment, validation, troubleshooting, and cleanup.",
    "difficulty": "Beginner",
    "topics": [
      "Kubernetes",
      "kubeadm",
      "containerd",
      "Calico",
      "Container Orchestration",
      "Linux",
      "VirtualBox"
    ],
    "estimatedTime": 120,
    "prerequisites": [
      "VirtualBox",
      "Ubuntu 20.04 or later",
      "2 virtual CPUs",
      "4 GB RAM",
      "25 GB disk space",
      "Internet access",
      "Basic Linux command-line familiarity"
    ],
    "repository": "walkthroughs/single-node-k8s-cluster",
    "authors": [
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "single-node-microk8s-cluster",
    "title": "Install a Single-Node MicroK8s Cluster on Ubuntu Server 26.04",
    "description": "Build a single-node Kubernetes cluster using MicroK8s on Ubuntu Server 26.04 in VirtualBox. Create the virtual machine, select MicroK8s during Ubuntu installation, configure user permissions, verify cluster readiness, and set up a kubectl alias for future Kubernetes labs.",
    "difficulty": "Beginner",
    "topics": [
      "Kubernetes",
      "MicroK8s",
      "Ubuntu",
      "Linux",
      "VirtualBox",
      "Container Orchestration",
      "kubectl"
    ],
    "estimatedTime": 60,
    "prerequisites": [
      "Oracle VirtualBox",
      "Ubuntu Server 26.04 installation image",
      "Host computer with 16 GB RAM or more recommended",
      "Hardware virtualization enabled in BIOS or UEFI",
      "2-4 virtual CPUs and 8 GB RAM available for the virtual machine",
      "At least 40 GB of available disk space",
      "Internet access",
      "Basic Linux command-line familiarity"
    ],
    "repository": "walkthroughs/single-node-microk8s-cluster",
    "authors": [
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      },
      {
        "name": "Nisha McDonnell",
        "url": "https://www.linkedin.com/in/nishapmcd"
      }
    ]
  },
  {
    "id": "aws-s3-public-access-auto-remediation",
    "title": "Event-Driven S3 Public Access Auto-Remediation Control",
    "description": "Implement an event-driven AWS security control that detects S3 public-access misconfigurations as they occur, evaluates the bucket’s live configuration, automatically restores required protections, and sends remediation evidence through Amazon SNS.",
    "difficulty": "Intermediate",
    "topics": [
      "AWS",
      "Cloud Security",
      "Detection Engineering",
      "Auto-Remediation",
      "Lambda",
      "Event-Driven Architecture",
      "Terraform"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "AWS Sandbox Account",
      "Terraform CLI",
      "Basic Python Proficiency",
      "Knowledge of IAM Policies",
      "Understanding of Amazon S3 Public Access Block"
    ],
    "repository": "walkthroughs/aws-s3-public-access-auto-remediation",
    "repositoryUrl": "https://github.com/devsecblueprint/aws-s3-public-access-auto-remediation",
    "authors": [
      {
        "name": "Sajid Shaikh",
        "url": "https://www.linkedin.com/in/shaikhsajid18/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "aws-preventative-control",
    "title": "Organization-Level Guardrails with AWS SCPs: Enforcing IMDSv2 for EC2",
    "description": "Implement a preventative security control using AWS Service Control Policies (SCPs) to enforce IMDSv2 usage across EC2 instances. This project demonstrates how to define organization-wide guardrails that block insecure configurations before they are deployed, ensuring consistent security posture across all AWS accounts.",
    "difficulty": "Intermediate",
    "topics": [
      "AWS",
      "Cloud Security",
      "Preventative Controls",
      "Service Control Policies",
      "EC2",
      "IAM",
      "Organizations"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "AWS Organizations Enabled",
      "Basic Understanding of IAM and SCPs",
      "Familiarity with EC2 Instance Metadata Service (IMDS)",
      "AWS CLI or Console Access",
      "Terraform Installed (>= 1.5.0)"
    ],
    "repository": "walkthroughs/aws-preventative-control",
    "repositoryUrl": "https://github.com/devsecblueprint/aws-org-scp-ec2-imdsv2-preventive-control",
    "authors": [
      {
        "name": "Chi Che",
        "url": "https://www.linkedin.com/in/chi-che/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-pipeline-aws",
    "title": "Cloud Native DevSecOps Pipeline on AWS",
    "description": "Build an automated CI/CD pipeline using Terraform Cloud to deploy containerized applications on AWS. This project integrates AWS CodePipeline, CodeBuild, and EKS with security tools like Snyk and Trivy for comprehensive vulnerability scanning.",
    "difficulty": "Intermediate",
    "topics": [
      "AWS",
      "Terraform Cloud",
      "DevSecOps",
      "EKS",
      "CI/CD",
      "Container Security"
    ],
    "estimatedTime": 180,
    "prerequisites": [
      "AWS Account",
      "GitHub Account",
      "Terraform CLI",
      "Docker",
      "Python 3.12+"
    ],
    "repository": "walkthroughs/devsecops-pipeline-aws",
    "repositoryUrl": "https://github.com/devsecblueprint/aws-devsecops-pipeline",
    "authors": [
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-pipeline-azure",
    "title": "Cloud-Native DevSecOps Pipeline on Azure",
    "description": "Establish a foundational Azure DevSecOps workflow. This project uses Terraform Cloud to provision Azure DevOps pipelines that automate the building, scanning, and deployment of containerized FastAPI applications into Azure Container Registry (ACR).",
    "difficulty": "Intermediate",
    "topics": [
      "Azure",
      "Azure DevOps",
      "Terraform Cloud",
      "CI/CD Automation",
      "Trivy & ZAP",
      "Container Registry"
    ],
    "estimatedTime": 180,
    "prerequisites": [
      "Azure Account",
      "GitHub Account",
      "Terraform CLI",
      "Azure CLI",
      "Python 3.12+"
    ],
    "repository": "walkthroughs/devsecops-pipeline-azure",
    "repositoryUrl": "https://github.com/devsecblueprint/azure-devsecops-pipeline",
    "authors": [
      {
        "name": "Timothy Hogue",
        "url": "https://www.linkedin.com/in/timothy-hogue/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-pipeline-gcp",
    "title": "Cloud Native DevSecOps Pipeline on GCP",
    "description": "Establish a foundational GCP DevSecOps workflow. This project uses Terraform Cloud to provision Cloud Build pipelines that automate the building, scanning, and deployment of containerized FastAPI applications into Google Cloud Run.",
    "difficulty": "Intermediate",
    "topics": [
      "GCP",
      "Cloud Build",
      "Cloud Run",
      "Terraform Cloud",
      "Snyk & Trivy",
      "Workload Identity Federation"
    ],
    "estimatedTime": 180,
    "prerequisites": [
      "GCP Project",
      "Terraform CLI",
      "gcloud CLI",
      "Docker",
      "Python 3.12+"
    ],
    "repository": "walkthroughs/devsecops-pipeline-gcp",
    "repositoryUrl": "https://github.com/devsecblueprint/gcp-devsecops-pipeline",
    "authors": [
      {
        "name": "Iman Crooks",
        "url": "https://www.linkedin.com/in/iman-crooks"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "k8s-nginx-gatekeeper",
    "title": "Deploying nginx and Enforcing Image Policies with Gatekeeper",
    "description": "Build on the Part 1 single-node cluster by deploying an existing nginx image with Deployment and Service YAML, scaling and validating the workload, then installing OPA Gatekeeper and testing a Chainguard image allowlist with compliant and noncompliant Deployments.",
    "difficulty": "Intermediate",
    "topics": [
      "Kubernetes",
      "nginx",
      "YAML",
      "Deployments",
      "Services",
      "OPA Gatekeeper",
      "Chainguard",
      "Admission Control"
    ],
    "estimatedTime": 120,
    "prerequisites": [
      "Part 1 single-node Kubernetes cluster or equivalent",
      "kubectl and curl",
      "Cluster administrator access",
      "Internet access"
    ],
    "repository": "walkthroughs/k8s-nginx-gatekeeper",
    "authors": [
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "aws-prowler-security-scanning-docker-compose",
    "title": "AWS Prowler Security Scanning with Docker Compose",
    "description": "Deploy Prowler locally using Docker Compose, connect it to an AWS account with read-only credentials, and run automated cloud security assessments. This walkthrough covers local deployment, AWS provider configuration, security scanning, findings analysis, compliance reporting, mutelists, and troubleshooting.",
    "difficulty": "Intermediate",
    "topics": [
      "AWS",
      "Prowler",
      "Docker Compose",
      "Cloud Security",
      "Security Scanning",
      "Compliance",
      "IAM",
      "CSPM"
    ],
    "estimatedTime": 120,
    "prerequisites": [
      "AWS Account",
      "GitHub Account",
      "Docker Desktop with Docker Compose v2",
      "Basic knowledge of AWS IAM",
      "Basic familiarity with Docker",
      "Terraform 1.5+ (Optional)",
      "AWS CLI (Optional)"
    ],
    "repository": "walkthroughs/aws-prowler-security-scanning-docker-compose",
    "repositoryUrl": "https://github.com/devsecblueprint/prowler-docker-walkthrough",
    "authors": [
      {
        "name": "Malik Dixon",
        "url": "https://www.linkedin.com/in/malik-dixon/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "tfc-aws-ec2-metadata-policy-violation",
    "title": "Enforce EC2 IMDSv2 with Terraform Cloud OPA Policies",
    "description": "Build a defense-in-depth control for Amazon EC2 Instance Metadata Service v2 (IMDSv2). This lab uses Terraform Cloud OPA policies to block noncompliant Terraform plans and an AWS Service Control Policy (SCP) to prevent EC2 launches that do not require IMDSv2 at the API layer.",
    "difficulty": "Intermediate",
    "topics": [
      "Terraform Cloud",
      "Open Policy Agent",
      "Rego",
      "Amazon EC2",
      "IMDSv2",
      "GitHub Actions"
    ],
    "estimatedTime": 120,
    "prerequisites": [
      "Terraform Cloud Account",
      "GitHub Account",
      "Basic knowledge of Terraform",
      "Basic familiarity with Open Policy Agent and Rego"
    ],
    "repository": "walkthroughs/tfc-aws-ec2-metadata-policy-violation",
    "repositoryUrl": "https://github.com/devsecblueprint/tfc-aws-ec2-metadata-policy-violation",
    "authors": [
      {
        "name": "Malik Dixon",
        "url": "https://www.linkedin.com/in/malik-dixon/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-home-lab",
    "title": "DevSecOps Home Lab: From Scratch to CI/CD",
    "description": "Build a comprehensive, multi-server DevSecOps environment. This lab covers setting up a complete toolchain including Gitea for version control, Jenkins for CI/CD, SonarQube and Trivy for security scanning, Nexus for artifact management, and a Prometheus/Grafana stack for full-stack monitoring.",
    "difficulty": "Advanced",
    "topics": [
      "DevSecOps",
      "Docker & Containerization",
      "CI/CD Pipelines",
      "Security Scanning",
      "Vulnerability Management",
      "Monitoring & Observability"
    ],
    "estimatedTime": 240,
    "prerequisites": [
      "Ubuntu 24.04 LTS",
      "Basic Linux Command Line Proficiency",
      "Hardware for two servers or VirtualBox for VMs"
    ],
    "repository": "walkthroughs/devsecops-home-lab",
    "authors": [
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  }
];
