/**
 * Pre-loaded walkthrough data for client-side use
 * This file is generated at build time and contains all walkthrough metadata
 * 
 * Generated by: scripts/generate-walkthroughs-data.ts
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 */

import type { Walkthrough } from '@/lib/types';

// This data is embedded at build time
export const WALKTHROUGHS_DATA: Walkthrough[] = [
  {
    "id": "aws-detective-control",
    "title": "Event-Driven S3 Public Access Detective Control",
    "description": "Implement an automated security control to catch S3 bucket misconfigurations as they happen. This project leverages CloudTrail and EventBridge to trigger a Python-based Lambda function that evaluates live bucket settings and sends actionable alerts via SNS.",
    "difficulty": "Beginner",
    "topics": [
      "AWS",
      "Cloud Security",
      "Detection Engineering",
      "Lambda",
      "Event-Driven Architecture",
      "Terraform"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "AWS Account",
      "Terraform CLI",
      "Basic Python Proficiency",
      "Knowledge of IAM Policies"
    ],
    "repository": "walkthroughs/aws-detective-control",
    "repositoryUrl": "https://github.com/devsecblueprint/aws-event-driven-s3-public-detective-control",
    "authors": [
      {
        "name": "Kosisochukwu Akaeze",
        "url": "https://www.linkedin.com/in/kosisochukwu-akaeze-a4853a1a7"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-pipeline-gha",
    "title": "GitHub Actions DevSecOps Pipeline",
    "description": "Build a fully automated DevSecOps pipeline using GitHub Actions. This lab integrates SAST with SonarCloud, DAST with ZAP, and container scanning with Trivy to secure a Python FastAPI application and publish it to the GitHub Container Registry (GHCR).",
    "difficulty": "Beginner",
    "topics": [
      "GitHub Actions",
      "SAST/DAST",
      "Trivy",
      "SonarCloud",
      "GHCR",
      "FastAPI"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "GitHub Account",
      "Basic knowledge of Docker",
      "Understanding of YAML for Workflows",
      "Python 3.12+"
    ],
    "repository": "walkthroughs/devsecops-pipeline-gha",
    "repositoryUrl": "https://github.com/devsecblueprint/python-fastapi",
    "authors": [
      {
        "name": "Timothy Hogue",
        "url": "https://www.linkedin.com/in/timothy-hogue/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "aws-preventative-control",
    "title": "Organization-Level Guardrails with AWS SCPs: Enforcing IMDSv2 for EC2",
    "description": "Implement a preventative security control using AWS Service Control Policies (SCPs) to enforce IMDSv2 usage across EC2 instances. This project demonstrates how to define organization-wide guardrails that block insecure configurations before they are deployed, ensuring consistent security posture across all AWS accounts.",
    "difficulty": "Intermediate",
    "topics": [
      "AWS",
      "Cloud Security",
      "Preventative Controls",
      "Service Control Policies",
      "EC2",
      "IAM",
      "Organizations"
    ],
    "estimatedTime": 90,
    "prerequisites": [
      "AWS Organizations Enabled",
      "Basic Understanding of IAM and SCPs",
      "Familiarity with EC2 Instance Metadata Service (IMDS)",
      "AWS CLI or Console Access",
      "Terraform Installed (>= 1.5.0)"
    ],
    "repository": "walkthroughs/aws-preventative-control",
    "repositoryUrl": "https://github.com/devsecblueprint/aws-org-scp-ec2-imdsv2-preventive-control",
    "authors": [
      {
        "name": "Chi Che",
        "url": "https://www.linkedin.com/in/chi-che/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-pipeline-aws",
    "title": "Cloud Native DevSecOps Pipeline on AWS",
    "description": "Build an automated CI/CD pipeline using Terraform Cloud to deploy containerized applications on AWS. This project integrates AWS CodePipeline, CodeBuild, and EKS with security tools like Snyk and Trivy for comprehensive vulnerability scanning.",
    "difficulty": "Intermediate",
    "topics": [
      "AWS",
      "Terraform Cloud",
      "DevSecOps",
      "EKS",
      "CI/CD",
      "Container Security"
    ],
    "estimatedTime": 180,
    "prerequisites": [
      "AWS Account",
      "GitHub Account",
      "Terraform CLI",
      "Docker",
      "Python 3.12+"
    ],
    "repository": "walkthroughs/devsecops-pipeline-aws",
    "repositoryUrl": "https://github.com/devsecblueprint/aws-devsecops-pipeline",
    "authors": [
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-pipeline-azure",
    "title": "Cloud-Native DevSecOps Pipeline on Azure",
    "description": "Establish a foundational Azure DevSecOps workflow. This project uses Terraform Cloud to provision Azure DevOps pipelines that automate the building, scanning, and deployment of containerized FastAPI applications into Azure Container Registry (ACR).",
    "difficulty": "Intermediate",
    "topics": [
      "Azure",
      "Azure DevOps",
      "Terraform Cloud",
      "CI/CD Automation",
      "Trivy & ZAP",
      "Container Registry"
    ],
    "estimatedTime": 180,
    "prerequisites": [
      "Azure Account",
      "GitHub Account",
      "Terraform CLI",
      "Azure CLI",
      "Python 3.12+"
    ],
    "repository": "walkthroughs/devsecops-pipeline-azure",
    "repositoryUrl": "https://github.com/devsecblueprint/azure-devsecops-pipeline",
    "authors": [
      {
        "name": "Timothy Hogue",
        "url": "https://www.linkedin.com/in/timothy-hogue/"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-pipeline-gcp",
    "title": "Cloud Native DevSecOps Pipeline on GCP",
    "description": "Establish a foundational GCP DevSecOps workflow. This project uses Terraform Cloud to provision Cloud Build pipelines that automate the building, scanning, and deployment of containerized FastAPI applications into Google Cloud Run.",
    "difficulty": "Intermediate",
    "topics": [
      "GCP",
      "Cloud Build",
      "Cloud Run",
      "Terraform Cloud",
      "Snyk & Trivy",
      "Workload Identity Federation"
    ],
    "estimatedTime": 180,
    "prerequisites": [
      "GCP Project",
      "Terraform CLI",
      "gcloud CLI",
      "Docker",
      "Python 3.12+"
    ],
    "repository": "walkthroughs/devsecops-pipeline-gcp",
    "repositoryUrl": "https://github.com/devsecblueprint/gcp-devsecops-pipeline",
    "authors": [
      {
        "name": "Iman Crooks",
        "url": "https://www.linkedin.com/in/iman-crooks"
      },
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  },
  {
    "id": "devsecops-home-lab",
    "title": "DevSecOps Home Lab: From Scratch to CI/CD",
    "description": "Build a comprehensive, multi-server DevSecOps environment. This lab covers setting up a complete toolchain including Gitea for version control, Jenkins for CI/CD, SonarQube and Trivy for security scanning, Nexus for artifact management, and a Prometheus/Grafana stack for full-stack monitoring.",
    "difficulty": "Advanced",
    "topics": [
      "DevSecOps",
      "Docker & Containerization",
      "CI/CD Pipelines",
      "Security Scanning",
      "Vulnerability Management",
      "Monitoring & Observability"
    ],
    "estimatedTime": 240,
    "prerequisites": [
      "Ubuntu 24.04 LTS",
      "Basic Linux Command Line Proficiency",
      "Hardware for two servers or VirtualBox for VMs"
    ],
    "repository": "walkthroughs/devsecops-home-lab",
    "authors": [
      {
        "name": "Damien Burks",
        "url": "https://damienjburks.com"
      }
    ]
  }
];
